# Site settings

title: Cajón filosófico 
author:
  name: 
  email: 
description: Un espacio de difusión de las humanidades digitales y su labor, así como de fragmentos filosóficos.

# Build settings
remote_theme: jekyll/minima
