# Site settings

title: Cajón filosófico 
author:
  name: 
  email: 
description: Un espacio de difusión de las humanidades humanidades y su labor, así como de fragmentos digitales.

# Build settings
remote_theme: jekyll/minima
